(part "RSCSK2243R3D02008U"
    (packageRef "RSCSK2243R3D02008U")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Elna")
    (property "Manufacturer_Part_Number" "RSCSK2243R3D02008U")
    (property "Mouser_Part_Number" "555-DSK3R3H224U-HL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Elna/RSCSK2243R3D02008U?qs=4ASt3YYao0VaMSApaTZjpQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "220 mF (EDLC) Supercapacitor 3.3 V Coin, Wide Terminals - Opposite Sides 200Ohm 1000 Hrs @ 60C")
    (property "Datasheet_Link" "https://www1.futureelectronics.com/doc/ELNA/RSCSK2243R3D02008U.pdf")
    (property "symbolName1" "RSCSK2243R3D02008U")
)
