(part "LD39200PU33R"
    (packageRef "SON95P300X300X100-7N-D")
    (interface
        (port "1" (symbPinId 1) (portName "OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "ADJ/SENSE") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "PG") (portType INOUT))
        (port "5" (symbPinId 5) (portName "EN") (portType INOUT))
        (port "6" (symbPinId 6) (portName "IN") (portType INOUT))
        (port "7" (symbPinId 7) (portName "EPAD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "LD39200PU33R")
    (property "Mouser_Part_Number" "511-LD39200PU33R")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/LD39200PU33R?qs=WHlX%252B%252B9%2FRwAl6%2FJDqRS1uw%3D%3D")
    (property "Arrow_Part_Number" "LD39200PU33R")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ld39200pu33r/stmicroelectronics?utm_currency=USD&region=nac")
    (property "Description" "LDO Voltage Regulators 2 A high PSRR ultra low drop linear regulator with reverse current protection")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/ld39200.pdf")
    (property "symbolName1" "LD39200PU33R")
)
